# Generated by Django 4.0.6 on 2022-07-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='date_of_completion',
        ),
    ]
