# Generated by Django 4.0.6 on 2022-07-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_one', '0002_remove_tasks_date_of_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.TextField(),
        ),
    ]
